### ISSUE TITLE
Problem with bitstring on Python 3.10

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp_secure_cert_mgr#9]
BitString was renamed to BitStream in Python 3.7+. I renamed in the IDF source and it seems to work.

jonsmirl@ares:~/aosp/esp-matter/examples/lowpan$ configure_esp_secure_cert.py -p /dev/ttyACM0 --keep_ds_data_on_host --efuse_key_id 1 --ca-cert cacert.pem --device-cert client.crt --private-key client.key --target_chip esp32c3 --secure_cert_type cust_flash_tlv --configure_ds
Traceback (most recent call last):
  File "/home/jonsmirl/esp/esp-idf/components/esptool_py/esptool/espefuse.py", line 15, in <module>
    import espressif.efuse.esp32 as esp32_efuse
  File "/home/jonsmirl/esp/esp-idf/components/esptool_py/esptool/espressif/efuse/esp32/__init__.py", line 1, in <module>
    from . import operations
  File "/home/jonsmirl/esp/esp-idf/components/esptool_py/esptool/espressif/efuse/esp32/operations.py", line 18, in <module>
    from . import fields
  File "/home/jonsmirl/esp/esp-idf/components/esptool_py/esptool/espressif/efuse/esp32/fields.py", line 17, in <module>
    from .. import base_fields
  File "/home/jonsmirl/esp/esp-idf/components/esptool_py/esptool/espressif/efuse/base_fields.py", line 14, in <module>
    from bitstring import BitArray, BitString, CreationError
ImportError: cannot import name 'BitString' from 'bitstring' (/home/jonsmirl/.espressif/python_env/idf4.4_py3.10_env/lib/python3.10/site-packages/bitstring.py)

**Comment by mahavirj** [comment]
This has been fixed on esptool side with https://github.com/espressif/esptool/commit/ee27a6437576797d5f58c31e1c39f3a232a71df0 but the fix shall appear in v4.5 release. For previous versions, we recommend using `bitstring>=3.1.6,<4` as done with https://github.com/espressif/esptool/commit/6d230f384fd13b757f6060f556a4cd1802c5dbef.

Additional reference:
https://github.com/espressif/esptool/issues/797
https://github.com/espressif/esptool/issues/807

Hope this helps!
